# ===== FRONTEND DOCKERFILE =====
FROM node:18

WORKDIR /app

# Kopiujemy package.json i package-lock.json
COPY package*.json ./

# Instalacja WSZYSTKICH zależności (bez cache)
RUN npm install --force
RUN npm install react-leaflet@4.2.1 leaflet@1.9.4 @types/leaflet@1.9.21 --force

# Skopiowanie reszty kodu
COPY . .

EXPOSE 3000

CMD ["npm", "start", "--", "--host", "0.0.0.0"]
