FROM node:18

WORKDIR /app

# Kopiuj pliki konfiguracyjne
COPY package*.json ./
COPY tsconfig.json ./

# Instaluj zależności
RUN npm install

# Kopiuj kod źródłowy
COPY . .

# Buduj aplikację
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]