FROM node:18

WORKDIR /app

# Kopiuj tylko package.json i package-lock.json (jeśli masz)
COPY package*.json ./

# Instaluj zależności (w tym react-scripts)
RUN npm install

# Kopiuj resztę plików projektu
COPY . .

# Buduj aplikację (tworzy folder build)
RUN npm run build

# Globalnie instaluj serve tylko do serwowania builda
RUN npm install -g serve

# Otwórz port 3000
EXPOSE 3000

# Serwuj zbudowaną aplikację z folderu build
CMD ["serve", "-s", "build", "-l", "3000"]
